name: Docker Image text2img

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      id : build
      run: |
       TAG=$(date +%s)
       echo ::set-output name=docker_tag::$TAG
       docker build . --file Dockerfile --tag text2img:$TAG
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: deploy to docker hub
      run: |
          docker tag text2img:${{ steps.build.outputs.docker_tag }}  ${{secrets.DOCKERHUB_USERNAME}}/text2img:${{ steps.build.outputs.docker_tag }}
          docker tag text2img:${{ steps.build.outputs.docker_tag }}  ${{secrets.DOCKERHUB_USERNAME}}/text2img
          docker images
          docker push ${{secrets.DOCKERHUB_USERNAME}}/text2img:${{ steps.build.outputs.docker_tag }}
          docker push ${{secrets.DOCKERHUB_USERNAME}}/text2img
